from __future__ import annotations

from typing import Any

import jax
import jax.numpy as jnp

from iqml.models.iqml import (
    IQMLConfig,
    IQMLEncoding,
    IQMLOutput,
    Params,
    _linear,
    _lstm_forward,
    _quantum_config,
    init_iqml_params,
    iqml_predict_from_quantum_features,
)
from iqml.quantum.circuits import run_pqc_batch


def init_nonrecurrent_iqml_params(key: jax.Array, config: IQMLConfig) -> Params:
    """Use the exact IQML parameter tree for strict parameter-count matching."""
    return init_iqml_params(key, config)


def nonrecurrent_iqml_encode(params: Params, x: jnp.ndarray, config: IQMLConfig) -> IQMLEncoding:
    """Encode with recurrent classical context but reset memory for theta generation.

    The parameter tree is identical to IQML. The only change is that quantum
    parameters are generated by applying the same LSTM cell independently to
    each time step, with hidden and cell states reset to zero. This removes
    recurrent layer-to-layer memory from the QNN parameter generator without
    changing the number of trainable parameters.
    """
    recurrent_hidden = _lstm_forward(params["lstm"], x, config.hidden_dim)
    classical_prediction = _linear(params["classical_head"], recurrent_hidden[:, -1, :])
    theta_features = _lstm_reset_forward(params["lstm"], x, config.hidden_dim)
    theta = jnp.pi * jnp.tanh(_linear(params["quantum_encoder"], theta_features))
    return IQMLEncoding(
        classical_prediction=classical_prediction,
        theta=theta,
        hidden_sequence=theta_features,
    )


def nonrecurrent_iqml_forward(params: Params, x: jnp.ndarray, config: IQMLConfig) -> IQMLOutput:
    encoded = nonrecurrent_iqml_encode(params, x, config)
    quantum_features = run_pqc_batch(encoded.theta, _quantum_config(config))
    prediction = iqml_predict_from_quantum_features(
        params,
        encoded.classical_prediction,
        quantum_features,
    )
    return IQMLOutput(
        prediction=prediction,
        classical_prediction=encoded.classical_prediction,
        quantum_features=quantum_features,
        theta=encoded.theta,
        hidden_sequence=encoded.hidden_sequence,
    )


def nonrecurrent_iqml_mse_loss(
    params: Params,
    x: jnp.ndarray,
    y: jnp.ndarray,
    config: IQMLConfig,
) -> jnp.ndarray:
    output = nonrecurrent_iqml_forward(params, x, config)
    return jnp.mean((output.prediction - y) ** 2)


def _lstm_reset_forward(params: dict[str, Any], x: jnp.ndarray, hidden_dim: int) -> jnp.ndarray:
    x = jnp.asarray(x, dtype=params["W"].dtype)
    batch_size, depth = x.shape[0], x.shape[1]
    zero_hidden = jnp.zeros((batch_size, depth, hidden_dim), dtype=params["W"].dtype)
    joined = jnp.concatenate([x, zero_hidden], axis=-1)
    gates = jnp.einsum("bti,ij->btj", joined, params["W"]) + params["b"]
    i, _f, g, o = jnp.split(gates, 4, axis=-1)
    next_c = jax.nn.sigmoid(i) * jnp.tanh(g)
    next_h = jax.nn.sigmoid(o) * jnp.tanh(next_c)
    return next_h
